### ISSUE TITLE
Änderung in Http für die Nutzung in CBPI

### ISSUE THREAD

**Issue by JamFfm** [emilio77/IThermometer#1]
Hi Emilio, ist es möglich das das iThemometer als HTTP sendet?
Ich denk da an dieses Format:

The other system need to push the data to the following endpoint of your CraftBeerPi server.
key = sensor key - alpha nummeric name without blanks
value = the new sensor value. Internaly handled as string

http://<RaspberryPi-IP-Addresse>:5000/api/httpsensor/<key>/<value>
down vote accepted Try putting your HTML snippet inside an ```HTML block like this:

Example URL:
http://192.168.178.37:5000/api/httpsensor/sensor1/10

Kommt vom HTTP Sensor Plugin von hier: https://github.com/craftbeerpi/http_sensor

Die Idee dahinter:
Ich träume schon länger von Funktemperaturfühlern die dann über CBPI Funksteckdosen ansteuern.
Ich habe 2 stück 7 Liter Glühweinkocher für das Läuterwasser. Damit es mir keine Sicherung raushaut stehen die etwas abseits vom Einkocher (somit vom CBPI) dort wo es einen Stromkreis mit anderer Sicherung gibt. Das ist aber nie richtig temperiert, muss da immer noch was kaltes zuschütten.
Ja ist jammern auf hohem Niveau aber es wäre genial wenn die iThermometer in CBPI eingebunden werden können.

Geht das was?

Grüße Jan

**Comment by emilio77** [comment]
Ganz bestimmt ist das möglich. Ob der Termometer jetzt UDP oder TCP/HTTP sendet ist ihm erst mal egal. Ich verstehe nur leider nicht wie das geht. Vielleicht findest du das raus.

**Comment by JamFfm** [comment]
Danke erstmal für die Rückmeldung. Wenn ich es je hinbekomme, es werden länge Nächte...

**Comment by emilio77** [comment]
Vielleicht kann dir auch Manuel hier weiterhelfen, wie eine Solche Nachricht hier aussehen muss. Ich selber benutze kein CBP.

**Comment by ollinator2000** [comment]
Ich dir eine erste Version per Pull Request gebaut. ;-) IP und Key sind noch hard coded , funktionieren aber einwandfrei ! ;-) 
Mir fehlt gerade die Zeit den Code schick zu machen .

Gruss
Olli
